//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS_Project
{
    using System;
    using System.Collections.Generic;
<<<<<<< HEAD
=======
    using System.ComponentModel;
>>>>>>> 27207772cc45460432e831b52f56b088c845a29f
    using System.ComponentModel.DataAnnotations;

    public partial class Trainer
    {
        [Required]
        public int trainerID { get; set; }
<<<<<<< HEAD
        [Display(Name = "Name of Trainer")]
=======
        [Required]
        [DisplayName("Trainer Name")]
>>>>>>> 27207772cc45460432e831b52f56b088c845a29f
        public string trainerName { get; set; }
        [Required]
        public int userID { get; set; }
        [Required]
        public int cohortID { get; set; }
    
        public virtual Cohort Cohort { get; set; }
        public virtual User User { get; set; }
    }
}
