//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UMS_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class User_ManagementDBEntities : DbContext
    {
        public User_ManagementDBEntities()
            : base("name=User_ManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cohort> Cohorts { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Stream> Streams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Trainer> Trainers { get; set; }
        public virtual DbSet<Trainer1> Trainer1 { get; set; }
    }
}
